import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="overscroll-x-none;">
      {/* スワイプバックの無効化 */}
      <body className={`${inter.className} mx-auto w-[1100px]`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
